acceuil/urls.py
from django.urls import path
from . import views

app_name = 'acceuil'
urlpatterns = [
    path('',views.index, name='index'),
    path('level/',views.level,name='level'),
    path('niveau/',views.niveau ,name='niveau'),

]

compte/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

from .forms import loginForm

app_name = 'compte'
urlpatterns = [
    path('inscription/', views.inscription, name='inscription'), 
    path('login/',auth_views.LoginView.as_view(template_name ='compte/login.html', redirect_authenticated_user=True, authentication_form = loginForm), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name ='compte/logout.html',next_page='/compte/login'), name='logout'),
    
]

eduarnaque/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('game/', include('game.urls')),
    path('', include('acceuil.urls')),
    path('admin/', admin.site.urls),
    path('compte/', include('compte.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

game/urls.py
from django.urls import path
from . import views

app_name = 'game'
urlpatterns = [
    path('liste/<int:id>/', views.liste, name='liste' ),
    path('etape/<int:sc_stage>/',views.etape, name='etape'),
    path('detail/<int:id>/',views.detail, name='detail'),
    path('questions/',views.questions, name='questions'),
    path('continu/', views.continu, name='continu' ),
    ]

acceuil/models.py
from django.db import models

# Create your models here.
class Level(models.Model):
    niv= {
        ('facile','facile'),
        ('moyen','moyen'),
        ('difficile','difficile'),

    }
    niveau = models.CharField(("niveau") ,choices=niv, max_length=50, default="facile")

    def __str__(self):
        return self.niveau
    

class Scenario(models.Model):
    niveau_sc = models.ForeignKey("Level", on_delete=models.CASCADE)
    titre = models.CharField(("titre"), max_length=50)
    img = models.ImageField(("img"),upload_to ='scenaio_img'  ,null= True, blank=True)
    description = models.TextField(('description'))

class Stage(models.Model):
    sc_stage = models.ForeignKey("Scenario", on_delete=models.CASCADE)
    img = models.ImageField(("img"), upload_to='stage_img',null= True, blank=True)
    titre = models.CharField(("titreS"), max_length=50)
    contenu = models.TextField(("contenu"))

class Quiz(models.Model):
    stage = models.ForeignKey("Stage" ,on_delete=models.CASCADE)
    question = models.CharField(("question"),max_length=50)
    res1 = models.CharField(("res1"),max_length=50)
    res2 = models.CharField(("res2"),max_length=50)
    res3 = models.CharField(("res3"),max_length=50)
    res4 = models.CharField(("res4"),max_length=50)
    reponse = models.CharField(("reponse"),max_length=50)

   

compte/models.py
from django.db import models

# Create your models here.

game/models.py
from django.db import models

# Create your models here.

acceuil/forms.py
from django import forms
from .models import Level

class LevelForm(forms.ModelForm):
   
    class Meta:
        model = Level
        fields = ('niveau',)

    # def niveau_choices(self):
        
    #     field = self['niveau']
    #     widget = field.field.widget

    #     attrs = {}
    #     auto_id = field.auto_id
    #     if auto_id and 'id' not in widget.attrs:
    #         attrs['id'] = auto_id

    #     name = field.html_name

    #     return widget.get_renderer(name, field.value(), attrs=attrs)

    
    

compte/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

class loginForm(AuthenticationForm):
    
        username = forms.CharField(label='username', widget=forms.TextInput(attrs={
            'class' : 'form-control',
        }))
        password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
            'class' : 'form-control',
        }))
        class Meta:
            model = User
            fields = ('username','password')

class inscriptionForm(UserCreationForm):
    username = forms.CharField(label='username', widget=forms.TextInput(attrs={
            'class' : 'form-control',
    }))
    email = forms.CharField(label='e-mail', widget=forms.EmailInput(attrs={
            'class' : 'form-control',
    }))
    fist_name = forms.CharField(label='fist name', widget=forms.TextInput(attrs={
            'class' : 'form-control',
    }))
    last_name = forms.CharField(label='last name', widget=forms.TextInput(attrs={
            'class' : 'form-control',
    }))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
            'class' : 'form-control',
    }))
    password2 = forms.CharField(label='Password comfirmation', widget=forms.PasswordInput(attrs={
            'class' : 'form-control',
    }))
    class Meta:
        model = User
        fields = ('username','email','fist_name','last_name','password1','password2')

acceuil/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from .forms import LevelForm
from .models import Level
from compte.forms import loginForm

# Create your views here.
def index(request):
    return render(request, 'acceuil/index.html')

def level(request):

    niv = Level.objects.all()
    form = LevelForm()
    con = loginForm()
    context = {
        'niv': niv,
        'con': con,
        'form': form,
        'niveau': request.GET.get('niveau')
    }
    return render(request, 'acceuil/level.html', context)

def niveau(request):
    return render(request, 'acceuil/niveau.html')

compte/views.py
from django.shortcuts import render,redirect
from .forms import inscriptionForm
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

# inscriptiom
def inscription(request):
    if request.user.is_authenticated:
        rdirect('acceuil:index')
    if request.method == 'POST':
        form = inscriptionForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = inscriptionForm()

    context = {
        'form': form,
    }
    return render(request, 'compte/inscription.html',context)

# connexion
def login(request):
    context = {
        'form': form,
    }
    return render(request, 'compte/login.html',context)

game/views.py
from django.shortcuts import render
from acceuil.models import Scenario, Stage,Level,Quiz

# Create your views here.
def liste(request, id):
    niv = Level.objects.all()
    sc = Scenario.objects.filter(niveau_sc = id)

    context = {
        'niv': niv,
        'sc': sc,
    }

    return render(request, 'game/liste.html', context)


# etape
def etape(request, sc_stage):
    stage = Stage.objects.filter(sc_stage = sc_stage)
    sc = Scenario.objects.all()

    context = {
        'stage': stage,
        'sc': sc,
    }
    return render(request, 'game/etape.html' ,context)

def detail(request, id):
    stage = Stage.objects.get(id=id)
    context = {
        'stage': stage,
    }
    return render(request, 'game/detail.html' ,context)


def questions(request):

    qu = Quiz.objects.all()
    context = {
        'qu':qu
    }
    return render(request, 'game/questionnaire.html', context)

def continu(request):
    return render(request, 'game/continue.html')

acceuil/templates/acceuil/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Acceuil{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    {% load static %}
    <script src="{% static 'acceuil/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'acceuil/js/jquery.min.js' %}"></script>
    <script src="{% static 'acceuil/js/popper.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'acceuil/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'acceuil/css/style.css' %}">
    
    
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4 ">
            <div class="container">
                <a class="navbar-brand" href="{% url 'acceuil:index' %}">Eduarnaque</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
    
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                        <a class="nav-link" href="/">Acceuil</a>
                        </li>

                        {% comment %} utilisateur_connecte {% endcomment %}
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="#">Forum</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Salle</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'compte:logout' %}">Deconnexion</a>
                            </li>
                            
                            {% comment %} utilisateur non connecte {% endcomment %}
                        {% else %}
                            <li class="nav-item">
                            <a class="nav-link" href="{% url 'compte:login' %}">Se connecter</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="{% url 'compte:inscription' %}">S'inscrire</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Aide</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Rechercher</button>
                    </form>
                </div>
            </div>
    </nav>
    </div>
    
</head>
<body>
    {% block body %}

    <section class="fontac">

        <div class="container ">
            <div class="row">
                <div class="col"></div>
                <div class="col"></div>
            </div>
            <div class="row">
                <div class="col position-absolute top-50 start-50 translate-middle p-5">
                    <h2>EDUARNAQUE</h2>
                    <p>Sur Eduarnaque, apprenez la cyber-securite en jouant</p>
                    <form class="d-flex" action="">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'game:liste' 1 %}" class="btn btn-primary">Continuer le jeux</a>  
                        {% else %}
                            <a href="{% url 'acceuil:level'  %}" class="btn btn-primary">Commencer le jeux</a>
                        {% endif %}
                        
                    </form>
                </div>
                <div class="col"></div>
            </div>
        </div>


    </section>
        


    {% endblock body %}
    
 
</body>
</html>

acceuil/templates/acceuil/level.html
{% extends 'acceuil/index.html' %}

{% block title %}niveau
{% endblock title %}

{% block body %} 

<div class="container position-absolute top-50 start-50 translate-middle">
        <div class="row">
            <div class="col-md-5 mx-auto">
                <form method="POST" action="{% url 'compte:login' %}" enctype="multipart/form-data">
                    <h1 class="text-center">connexion</h1>
                    {% if con.non_field_errors %}
                        {% for error in con.non_field_errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in con %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text }}</p>
                            {% endif %}
                            {% if field.errors %}
                               {% for error in field.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                        <div class="p-2">
                            <input type="submit" value="submit" class="btn btn-primary ">
                            <a href="{% url 'game:liste' 1 %}" class="btn btn-primary">jouer sans connexion</a>
                        </div>
                        <p>vous n'avez pas de compte ?<br>
                            <a href="{% url 'compte:inscription' %}" class="btn btn-primary">S'inscrire</a>
                        </p>
                        
                </form>
            </div>
        </div>

    </div>


    

{% endblock body %}

acceuil/templates/acceuil/niveau.html
{% extends 'acceuil/index.html' %}

{% block title %}liste
{% endblock title %}


{% block body %}

    <script type="text/javascript">
      $(document).ready(function(){
        $("input[type='button']").click(function(){
          var val = $("input[name='niveau']:checked").val();
          if(val){
            var e.document.getElementById("niv").InnerHTML = "val";
          }
        });
        
      });
      
    </script>
  </head> 
  <body>
    <h5>Quel est votre langage de programmation préféré?</h5>
    <p> 
      <label><input type="radio" name="niveau" value="1">facile</label><br> 
      <label><input type="radio" name="niveau" value="2">moyen</label><br>
      <label><input type="radio" name="niveau" value="3">difficile</label><br>
     
    </p>
    <input type="button" value="Continuer">
    <p id="div"></p>

{% endblock body %}

compte/templates/compte/inscription.html
{% extends 'acceuil/index.html' %}

{% block title %}inscription
{% endblock title %}

{% block body %}

     <div class="container position-absolute top-50 start-50 translate-middle">
        <h1 class="text-center">inscription</h1>
        <div class="row">
            <div class="col-md-5 mx-auto">
                <form method="POST"  enctype="multipart/form-data">
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text }}</p>
                            {% endif %}
                            {% if field.errors %}
                               {% for error in field.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                        <div class="p-2">
                            <input type="submit" value="submit" class="btn btn-primary ">
                        </div>
                      
                </form>
            </div>
        </div>
    </div>

   
{% endblock body %}

compte/templates/compte/login.html
{% extends 'acceuil/index.html' %}

{% block title %}login
{% endblock title %}

{% block body %} 


    <div class="container position-absolute top-50 start-50 translate-middle">
        <h1 class="text-center">connexion</h1>
        <div class="row">
            <div class="col-md-5 mx-auto">
                <form method="POST" enctype="multipart/form-data">
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text }}</p>
                            {% endif %}
                            {% if field.errors %}
                               {% for error in field.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                        <div class="p-2">
                            <input type="submit" value="submit" class="btn btn-primary ">
                        </div>
                        
                </form>
            </div>
        </div>

    </div>


   
{% endblock body %}

game/templates/game/detail.html
{% extends 'acceuil/index.html' %}

{% block title %}liste
{% endblock title %}

{% block body %}

<div class="container">
    <div class="row">
     <div class="col">
        <div class="row ">
                <div class="card">
                <div class="row">
                    <div class="col">
                            <div class="card-body">      
                                    <h5 class="card-title">{{ stage.titre }}</h5>
                                    <p class="card-text">{{ stage.contenu }}</p>
                                    <a href="{% url 'game:questions' %}" class="btn btn-primary">Questions</a>
                            </div>
                    </div>
                    <div class="col">
                        {% if stage.img %}
                            <img src="{{stage.img.url}}" class="card-img-top" alt="">
                        {% endif %}
                    </div>
                </div>
            
            
                
            </div>
                

        </div>
     </div>
    </div>
</div>
           

{% endblock body %}

game/templates/game/etape.html
{% extends 'acceuil/index.html' %}

{% block title %}liste
{% endblock title %}

{% block body %}

    <div class="container">
    <div class="row">
     <div class="col-9">
        <div class="row row-cols-md-3 row-cols-sm-1">
                {% for st in stage %}
                    <div class="card" style="width: 18rem">
                    
                    {% if st.img %}
                         <img src="{{st.img.url}}" class="card-img-top" alt="">
                    {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title"> etape {{st.id}}</h5>
                                    <p class="card-text">{{st.titre}}</p>
                                    <a href="{% url 'game:detail' st.id %}" class="btn btn-primary">Ouvrir</a>
                                </div>
                        </div>
                {% endfor %}

        </div>
    </div>
            
    <div class="col-3">

         <h5>Liste des etapes</p>
        {% for s in stage %}
            <div class="row row-cols-md-2 row-cols-sm-1">
                <p><a href="{% url 'game:detail' s.id %}" class="btn btn-primary">etape {{st.id}}</a></p>
            </div>
            
        {% endfor %}     
         
    </div>
           
           
    </div>
    </div>
           

{% endblock body %}

game/templates/game/liste.html
{% extends 'acceuil/index.html' %}

{% block title %}liste
{% endblock title %}
{% load static %}
{% block body %}
    <div class="container">
    <div class="row">
     <div class="col-9">
        <div class="row row-cols-md-3 row-cols-sm-1">
                {% for s in sc %}
                    <div class="card" style="width: 18rem">
                                
                                <img src="{{s.img.url}}" class="card-img-top" alt="">
                                
                                <div class="card-body">
                                    <h5 class="card-title">{{s.titre}}</h5>
                                    <p class="card-text">{{s.description}}</p>
                                    <a href="{% url 'game:etape' s.id %}" class="btn btn-primary">Ouvrir</a>
                                </div> 
                        </div>
                {% endfor %}

        </div>
    </div>
            
    <div class="col-3">

         <h5>Liste de scenarios</p>
        {% for s in sc %}
            <div class="row row-cols-md-2 row-cols-sm-1">
                <p><a href="{% url 'game:etape' s.id %}" class="btn btn-primary">Scenario {{s.id}}</a></p>
            </div>
            
        {% endfor %}     
         
    </div>
           
           
    </div>
    </div>
           
       
{% endblock body %}

game/templates/game/questionnaire.html
{% extends 'acceuil/index.html' %}

{% block title %}liste
{% endblock title %}


{% block body%}
    
    <script>
    
    </script>
    <div class="container">
        <h1>Questions</h1>
        <div>
            {% for i in qu %}
                <table>
                <tr>
                    <td class="text-primary">{{i.id}} ) {{i.question}}</td>
                </tr>
                <tr>
                    <td><input type="radio" class="rb" name={{i.id}} id="res1" value="{{i.res1}}">{{i.res1}}</td>
                </tr>
                <tr>
                    <td><input type="radio" class="rb" name={{i.id}} id="res2" value="{{i.res2}}">{{i.res2}}</td>
                </tr>
                <tr>
                    <td><input type="radio" class="rb" name={{i.id}} id="res3" value="{{i.res3}}">{{i.res3}}</td>
                </tr>
                <tr>
                    <td><input type="radio" class="rb" name={{i.id}} id="res1" value="{{i.res1}}">{{i.res4}}</td>
                </tr>
                <tr>
                    <td><input type="radio" class="rb" name={{i.id}} id="reponse" value="{{i.reponse}}">{{i.reponse}}</td>
                </tr>
            </table>
            {% endfor %}
            
        </div>
    </div>

{% endblock body%}